package userinterface.veterinarianRole;

import model.enterprise.Enterprise;
import model.organization.TestingLabOrganization;
import model.organization.Organization;
import model.userAccount.User;
import model.taskbuffer.PawPatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private User userAccount;
    private PawPatientTreatmentWorkRequest patientTreatmentWorkRequest;

    public RequestLabTestJPanel(JPanel userProcessContainer, User account, Enterprise enterprise, PawPatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
        txt3.setText(enterprise.getName());
        txt2.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        txt3 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt2.setBackground(new java.awt.Color(102, 102, 0));
        txt2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("Request Test");
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Message:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, -1));
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, 30));

        backJButton.setBackground(new java.awt.Color(102, 102, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        txt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt3.setText("<value>");
        add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 20));

        txt7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt7.setText("Enterprise :");
        add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Paw Lab Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Paw's Lab Test Request ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/docdog.jpg"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 510, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed

        String labType = txt5.getText().trim();
        String message = txt1.getText().trim();

        if (labType.equals("")) {
            JOptionPane.showMessageDialog(null, "Lap type is required!");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is required");
            return;
        }

        patientTreatmentWorkRequest.setLabTestMessage(message);
        patientTreatmentWorkRequest.setSender(userAccount);
        patientTreatmentWorkRequest.setStatus("SentToLab");
        patientTreatmentWorkRequest.setReceiver(null);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationsDirectory()) {
            if (organization instanceof TestingLabOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            JOptionPane.showMessageDialog(null, "Lab request sent");
            txt1.setText("");
            txt5.setText("");
            txt2.setEnabled(false);
        }

    }//GEN-LAST:event_txt2ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VeterinarianWorkAreaJPanel dwjp = (VeterinarianWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt1;
    private javax.swing.JButton txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JTextField txt5;
    private javax.swing.JLabel txt7;
    // End of variables declaration//GEN-END:variables
}
