package userinterface.veterinarianRole;
import model.userAccount.User;
import model.taskbuffer.AccountantBillingRequest;
import model.taskbuffer.PawPatientTreatmentWorkRequest;
import java.awt.CardLayout;
import model.PawcareSystem;
import model.enterprise.Enterprise;
import model.organization.BillingOrganization;
import model.organization.Organization;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RequestBillingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private User userAccount;
    private Enterprise enterprise;
    private PawPatientTreatmentWorkRequest patientTreatmentWorkRequest;
    private PawcareSystem ecoSystem;
    private double consultationCharges = 50;

    
    RequestBillingJPanel(JPanel userProcessContainer, User userAccount, Enterprise enterprise, PawPatientTreatmentWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patientTreatmentWorkRequest = workRequest;
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMedicationCharges = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLabCharges = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMiscellaneousCharges = new javax.swing.JTextField();
        btnSendBillingRequest = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Billing Request");
        add(jLabel1);
        jLabel1.setBounds(251, 16, 230, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PAW PATIENT INFORMATION");
        add(jLabel6);
        jLabel6.setBounds(250, 70, 190, 15);

        txt1.setEditable(false);
        add(txt1);
        txt1.setBounds(200, 122, 131, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("First Name :");
        add(jLabel7);
        jLabel7.setBounds(101, 130, 90, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Last Name :");
        add(jLabel10);
        jLabel10.setBounds(120, 160, 71, 15);

        txt2.setEditable(false);
        add(txt2);
        txt2.setBounds(200, 160, 131, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Assigned Doctor :");
        add(jLabel8);
        jLabel8.setBounds(360, 120, 109, 20);

        txt5.setEditable(false);
        add(txt5);
        txt5.setBounds(480, 120, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient Id:");
        add(jLabel2);
        jLabel2.setBounds(360, 160, 66, 20);

        txt3.setEditable(false);
        add(txt3);
        txt3.setBounds(480, 160, 131, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("BILLING INFORMATION");
        add(jLabel3);
        jLabel3.setBounds(260, 210, 170, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Consultaion Charges (USD) :");
        add(jLabel4);
        jLabel4.setBounds(20, 250, 173, 21);

        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        add(txt7);
        txt7.setBounds(200, 250, 82, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Medication Charges (USD):");
        add(jLabel5);
        jLabel5.setBounds(30, 300, 163, 21);
        add(txtMedicationCharges);
        txtMedicationCharges.setBounds(200, 300, 82, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lab Test Charges (USD) :");
        add(jLabel11);
        jLabel11.setBounds(320, 250, 152, 21);

        txtLabCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabChargesActionPerformed(evt);
            }
        });
        add(txtLabCharges);
        txtLabCharges.setBounds(490, 250, 82, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Other Charges (USD):");
        add(jLabel12);
        jLabel12.setBounds(320, 300, 131, 17);
        add(txtMiscellaneousCharges);
        txtMiscellaneousCharges.setBounds(490, 300, 82, 23);

        btnSendBillingRequest.setBackground(new java.awt.Color(102, 102, 0));
        btnSendBillingRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSendBillingRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSendBillingRequest.setText("Send Billing Request");
        btnSendBillingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillingRequestActionPerformed(evt);
            }
        });
        add(btnSendBillingRequest);
        btnSendBillingRequest.setBounds(280, 360, 144, 32);

        backBtn.setBackground(new java.awt.Color(102, 102, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(45, 25, 75, 21);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doc5 (2).jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel9);
        jLabel9.setBounds(600, 50, 560, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabChargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabChargesActionPerformed

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void btnSendBillingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillingRequestActionPerformed
        String consultationCharge = txt7.getText().trim();
        String labChargesStr = txtLabCharges.getText();
        String miscellaneouschargesStr = txtMiscellaneousCharges.getText();
        String medicationChargesStr = txtMedicationCharges.getText();
        if (consultationCharge.equals("") || labChargesStr.equals("") || miscellaneouschargesStr.equals("") || medicationChargesStr.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            
            try {
                Double.parseDouble(consultationCharge);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter only digits");
                return;
            }
            
            try {
                Integer.parseInt(labChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter only digits");
                return;
            }
            try {
                Integer.parseInt(miscellaneouschargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter only digits");
                return;
            }
            try {
                Integer.parseInt(medicationChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter only digits");
                return;
            }
            double labCharges = Double.parseDouble(labChargesStr);
            double miscellaneouscharges = Double.parseDouble(miscellaneouschargesStr);
            double medicationCharges = Double.parseDouble(medicationChargesStr);
            double billingAmount = labCharges + consultationCharges + medicationCharges + miscellaneouscharges;
          

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed further?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setStatus("Consultation Completed");

                AccountantBillingRequest accountantBillingRequest = new AccountantBillingRequest();
                accountantBillingRequest.setBillingAmount(billingAmount);
                

                accountantBillingRequest.setSender(userAccount);
                accountantBillingRequest.setStatus("Sent");
                accountantBillingRequest.setPatient(patientTreatmentWorkRequest.getPatient());

                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationsDirectory()) {
                    if (organization instanceof BillingOrganization) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getWorkRequests().add(accountantBillingRequest);
                    userAccount.getWorkQueue().getWorkRequests().add(accountantBillingRequest);
                }

                JOptionPane.showMessageDialog(null, "Prescription submitted successfully");
                btnSendBillingRequest.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btnSendBillingRequestActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VeterinarianWorkAreaJPanel dwjp = (VeterinarianWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSendBillingRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txtLabCharges;
    private javax.swing.JTextField txtMedicationCharges;
    private javax.swing.JTextField txtMiscellaneousCharges;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        txt1.setText(patientTreatmentWorkRequest.getPatient().getPatientFirstName());
        txt2.setText(patientTreatmentWorkRequest.getPatient().getPatientLastName());
        txt3.setText(String.valueOf(patientTreatmentWorkRequest.getPatient().getPatientId()));
        txt5.setText(patientTreatmentWorkRequest.getAssignedDoctor().getEmployee().getName());
        txt7.setText(String.valueOf(consultationCharges));

    }
}
