package userinterface.HealthcareAccountantRole;

import model.PawcareSystem;
import model.enterprise.Enterprise;
import model.enterprise.HealthCareEnterprise;
import model.enterprise.PawInsuranceEnterprise;
import model.insurance.Insurance;
import model.insuranceCustomer.InsuranceCustomer;
import model.network.Network;
import model.organization.DoctorOrganization;
import model.organization.Organization;
import model.patient.PawPatient;
import model.userAccount.User;
import model.taskbuffer.PawPatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class CreateAppointmentJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private User userAccount;
    private Enterprise enterprise;
    private PawcareSystem ecosystem;
    private String patientId;

    /**
     * Creates new form CreateAppointmentJPanel
     */
    CreateAppointmentJPanel(JPanel userProcessContainer, User userAccount, Enterprise enterprise, PawcareSystem ecoSystem, String patientId) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecoSystem;
        this.patientId = patientId;
        
        populateField();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtPatientId11 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPatientSSN = new javax.swing.JTextField();
        btnFindPatient = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioBtnPatientInsuranceYes = new javax.swing.JRadioButton();
        radioBtnPatientInsuranceNo = new javax.swing.JRadioButton();
        lblHavePolicy = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        lblInsCompany = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txtReasonForVisit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblPolicyNum = new javax.swing.JLabel();
        txtPolicyNum = new javax.swing.JTextField();
        btnFindInsurance = new javax.swing.JButton();
        txtInsuranceCompany = new javax.swing.JTextField();
        txtPolicyName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        lblCoverage = new javax.swing.JLabel();
        txtCoverage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPatientIdentifier = new javax.swing.JTextField();
        btnResetPolicyNum = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();

        jLabel14.setText("Middle Name :");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREATE APPOINTMENT");

        btnBack.setBackground(new java.awt.Color(102, 102, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Already registered? Provide Owner's SSN: ");

        btnFindPatient.setBackground(new java.awt.Color(102, 102, 0));
        btnFindPatient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFindPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPatient.setText("Find Patient");
        btnFindPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPatientActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("First Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Last Name :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("SSN :");

        txtHomePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomePhoneActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Owner's Phone Number:");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Age :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Dog's Sex :");

        buttonGroup2.add(radioBtnMale);
        radioBtnMale.setText("M");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioBtnFemale);
        radioBtnFemale.setText("F");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Dog's Insaurance");

        buttonGroup1.add(radioBtnPatientInsuranceYes);
        radioBtnPatientInsuranceYes.setText("Yes");
        radioBtnPatientInsuranceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnPatientInsuranceNo);
        radioBtnPatientInsuranceNo.setText("No");
        radioBtnPatientInsuranceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceNoActionPerformed(evt);
            }
        });

        lblHavePolicy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHavePolicy.setText("Dog has Insurance?:");

        lblPolicyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPolicyName.setText("Policy Name :");

        lblInsCompany.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInsCompany.setText("Insurance Company :");

        btnCreate.setBackground(new java.awt.Color(102, 102, 0));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Dog's  Condition");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("MEDICAL CONDITION");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        lblPolicyNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPolicyNum.setText(" Insurance Policy Number:");

        txtPolicyNum.setEnabled(false);
        txtPolicyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPolicyNumActionPerformed(evt);
            }
        });

        btnFindInsurance.setBackground(new java.awt.Color(102, 102, 0));
        btnFindInsurance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFindInsurance.setText("Find Policy");
        btnFindInsurance.setEnabled(false);
        btnFindInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInsuranceActionPerformed(evt);
            }
        });

        lblCoverage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCoverage.setText(" Insurance Coverage % :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Patient ID / Visit ID :");

        btnResetPolicyNum.setBackground(new java.awt.Color(102, 102, 0));
        btnResetPolicyNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnResetPolicyNum.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPolicyNum.setText("Reset Policy Number");
        btnResetPolicyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPolicyNumActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.setText("Patient Owner's Email:");

        txtPatientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBtnFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(389, 389, 389))
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatientSSN)
                                    .addComponent(txtPatientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnFindPatient)))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHavePolicy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnPatientInsuranceYes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnPatientInsuranceNo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 70, Short.MAX_VALUE)
                                .addComponent(lblPolicyNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPolicyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindInsurance)
                                .addGap(26, 26, 26)
                                .addComponent(btnResetPolicyNum))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInsCompany)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCoverage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPolicyName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(273, 273, 273)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(204, 204, 204))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(620, 620, 620)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHavePolicy)
                            .addComponent(radioBtnPatientInsuranceYes)
                            .addComponent(radioBtnPatientInsuranceNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPatientSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFindPatient)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPatientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(radioBtnMale)
                            .addComponent(radioBtnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPolicyNum)
                            .addComponent(txtPolicyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindInsurance)
                            .addComponent(btnResetPolicyNum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPolicyName)
                            .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsCompany)
                            .addComponent(txtInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoverage)
                            .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePhoneActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void radioBtnPatientInsuranceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceYesActionPerformed
        lblPolicyNum.setEnabled(true);
        btnFindInsurance.setEnabled(true);
        txtPolicyNum.setEnabled(true);

    }//GEN-LAST:event_radioBtnPatientInsuranceYesActionPerformed

    private void radioBtnPatientInsuranceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceNoActionPerformed
        
        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);
        
        txtCoverage.setEnabled(false);
        
        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);
        
        lblPolicyName.setEnabled(false);
    }//GEN-LAST:event_radioBtnPatientInsuranceNoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        if (txtFirstName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter first name");
            return;
        }
        if (txtLastName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter last name");
            return;
        }
        if (buttonGroup2.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Select gender");
            return;
        }
        if (txtHomePhone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Dog Owner's phone number");
            return;
        }
        if (txtSSN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Owner's SSN");
            return;
        }
        if (txtAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide dog age");
            return;
        }
        if (txtAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide address");
            return;
        }
        
        if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Does your Dog have Insaurance");
            return;
        }
        
        if (txtReasonForVisit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Dog's condition");
            return;
            
        }
        if (txtPatientEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Owner's Email ID");
            return;
            
        }
        if (!usernamePatternCorrect(txtPatientEmail.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Invalid Email ID");
            
        }
        else {
            
            String registrationDate = txtDate.getText().trim();
            
            String firstName = txtFirstName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String gender = "Male";
            if (radioBtnFemale.isSelected()) {
                gender = "Female";
            } 
            String phoneNo = txtHomePhone.getText().trim();
            
            if (!phonePatternCorrect()) {
                JOptionPane.showMessageDialog(null, "/* Following are valid phone number examples */             \n"
                        + "              \"1234567890\", \"123-456-7890\", \"(123)4567890\", \"(123)456-7890\",\n"
                        + "              /* Following are invalid phone numbers */ \n"
                        + "              \"(1234567890)\",\"123)4567890\", \"12345678901\", \"(1)234567890\",");
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.RED));
                
                return;
            }
            
            if (phonePatternCorrect()) {
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                
            }
            
            String ssn = txtSSN.getText().trim();
            
            if (!ssnPatternCheck()) {
                JOptionPane.showMessageDialog(null, "Invalid SSN");
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.RED));
                
                return;
            }
            
            if (ssnPatternCheck()) {
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                
            }
            
            String age = txtAge.getText().trim();
            
            try {
                Integer.parseInt(age);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid Age");
                return;
            }
            
            String address = txtAddress.getText().trim();
            boolean hasInsurance = false;
            
            String policyNumber = txtPolicyNum.getText().trim();
            if (radioBtnPatientInsuranceYes.isSelected()) {
                if (policyNumber.equals("")) {
                    JOptionPane.showMessageDialog(null, "Enter policy Number");
                    return;
                }
                
                if (txtPolicyName.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Invalid Policy Number");
                    return;
                }
            }
            String insuranceCompany = String.valueOf(txtInsuranceCompany.getText());
            String policyName = String.valueOf(txtPolicyName.getText());
            String coverString = txtCoverage.getText().trim();
            double coverage = coverString.equals("") ? 0 : Double.parseDouble(txtCoverage.getText().trim());
            
            String reasonForVisit = txtReasonForVisit.getText().trim();
            
            if (hasInsurance) {
                if (txtPolicyNum.getText().equals("")) {
                    return;
                }
            }
            
            Insurance insurance = new Insurance(policyName, insuranceCompany, coverage);
            InsuranceCustomer insuranceCustomer = new InsuranceCustomer(insurance, policyNumber);
            
            HealthCareEnterprise healthCenterEnterprise = (HealthCareEnterprise) enterprise;
            PawPatient patient = new PawPatient();
            
            patient.setAppointmentDate(txtDate.getText());
            patient.setPatientId(patientId);
            patient.setPatientFirstName(firstName);
            patient.setPatientLastName(lastName);
            patient.setGender(gender);
            patient.setPatientEmail(txtPatientEmail.getText().trim());
            
            patient.setContactNumber(phoneNo);
            patient.setPatientAge(age);
            patient.setSocialSecurityNumber(ssn);
            patient.setAddress(address);
            
            patient.setInsuranceCustomer(insuranceCustomer);
            
            healthCenterEnterprise.getPatientDirectory().getPatients().add(patient);
            
            PawPatientTreatmentWorkRequest patientTreatmentWorkRequest = new PawPatientTreatmentWorkRequest(registrationDate, reasonForVisit, patient);
            patientTreatmentWorkRequest.setStatus("Waiting for Doctor");
            //   patientTreatmentWorkRequest.setSender(userAccount);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationsDirectory()) {
                if (organization instanceof DoctorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                refresh();
                JOptionPane.showMessageDialog(null, "Patient Registered Successfully");
            }
            
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AccountantWorkAreaJPanel dwjp = (AccountantWorkAreaJPanel) component;
        dwjp.populateAllPatientsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPatientActionPerformed
        
        boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<Network> networks = ecosystem.getNetworks();
        List<HealthCareEnterprise> healthCenterEnterprises = new ArrayList<>();
        
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCareEnterprise) {
                    healthCenterEnterprises.add((HealthCareEnterprise) enterprise);
                }
            }
        }
        
        for (HealthCareEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<PawPatient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (PawPatient patient : patients) {
                if (ssn.equals(patient.getSocialSecurityNumber())) {
                    autopopulateFields(patient);
                    isPatientFound = true;
                }
                
            }
        }
        
        if (!isPatientFound) {
            JOptionPane.showMessageDialog(null, "No patient Found");
        }
    }//GEN-LAST:event_btnFindPatientActionPerformed

    private void btnFindInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInsuranceActionPerformed
        String insurancePolicyNumber = txtPolicyNum.getText().trim();
        String ssn = txtSSN.getText().trim();
        List<PawInsuranceEnterprise> insuranceEnterprises = new ArrayList<>();
        InsuranceCustomer matchedCustomer = null;
        
        List<Network> networks = ecosystem.getNetworks();
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof PawInsuranceEnterprise) {
                    insuranceEnterprises.add((PawInsuranceEnterprise) enterprise);
                }
            }
        }
        
        for (PawInsuranceEnterprise insuranceCompanyEnterprise : insuranceEnterprises) {
            List<InsuranceCustomer> insuranceCustomers = insuranceCompanyEnterprise.getInsuranceCustomerDirectory().getInsuranceCustomers();
            for (InsuranceCustomer insuranceCustomer : insuranceCustomers) {
                if (insurancePolicyNumber.equals(insuranceCustomer.getInsurancePolicyNumber()) && ssn.equals(insuranceCustomer.getSsn())) {
                    matchedCustomer = insuranceCustomer;
                    
                }
            }
        }
        
        if (matchedCustomer != null) {
            txtInsuranceCompany.setText(matchedCustomer.getInsurance().getInsuranceCompany());
            txtPolicyName.setText(matchedCustomer.getInsurance().getPolicyName());
            //  txtPolicyNo.setText(matchedCustomer.getInsurancePolicyNumber());
            txtCoverage.setText(String.valueOf(matchedCustomer.getInsurance().getCoverage()));
            txtPolicyNum.setEnabled(false);
            txtSSN.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Policy number does not match with provided SSN");
            txtInsuranceCompany.setText("");
            txtPolicyName.setText("");
            txtCoverage.setText("");
            txtPolicyNum.setText("");
            return;
        }
    }//GEN-LAST:event_btnFindInsuranceActionPerformed

    private void btnResetPolicyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPolicyNumActionPerformed
        txtPolicyNum.setEnabled(true);
        txtSSN.setEnabled(true);
        txtPolicyNum.setText("");
        txtPolicyName.setText("");
        txtInsuranceCompany.setText("");
        txtCoverage.setText("");
        

    }//GEN-LAST:event_btnResetPolicyNumActionPerformed

    private void txtPatientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientEmailActionPerformed

    private void txtPolicyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPolicyNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPolicyNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFindInsurance;
    private javax.swing.JButton btnFindPatient;
    private javax.swing.JButton btnResetPolicyNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblHavePolicy;
    private javax.swing.JLabel lblInsCompany;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNum;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JRadioButton radioBtnPatientInsuranceNo;
    private javax.swing.JRadioButton radioBtnPatientInsuranceYes;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtInsuranceCompany;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientId11;
    private javax.swing.JTextField txtPatientIdentifier;
    private javax.swing.JTextField txtPatientSSN;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyNum;
    private javax.swing.JTextField txtReasonForVisit;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

    private void populateField() {
        LocalDateTime localTimeUpdate = LocalDateTime.now();
        DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy hh:mm:ss");
        txtDate.setText(localTimeUpdate.format(dateTimeFormat));
        
        txtPatientIdentifier.setText(patientId);
        
        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);
        
        txtCoverage.setEnabled(false);
        
        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);
        
        lblPolicyName.setEnabled(false);
    }
    
    private void refresh() {
        
        txtPatientIdentifier.setText(UUID.randomUUID().toString().substring(0, 7));
        txtFirstName.setText("");
        txtLastName.setText("");
        txtHomePhone.setText("");
        txtAge.setText("");
        txtSSN.setText("");
        txtAddress.setText("");
        txtReasonForVisit.setText("");
        txtPatientEmail.setText("");
        txtPolicyName.setText("");
        txtPolicyNum.setText("");
        txtCoverage.setText("");
        txtInsuranceCompany.setText("");
    }
    
    private boolean phonePatternCorrect() {
        
        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(txtHomePhone.getText());
        
        boolean b = false;
        
        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }
        
        return b;
    }
    
    private boolean ssnPatternCheck() {
        
        Pattern pattern = Pattern.compile("^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
        Matcher matcher = pattern.matcher(txtSSN.getText());
        
        boolean b = false;
        
        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }
        
        return b;
    }
    
    private void autopopulateFields(PawPatient patient) {
        txtFirstName.setText(patient.getPatientFirstName());
        txtLastName.setText(patient.getPatientLastName());
        txtPatientIdentifier.setText(patient.getPatientId());
        txtHomePhone.setText(patient.getContactNumber());
        txtSSN.setText(patient.getSocialSecurityNumber());
        txtAge.setText(patient.getPatientAge());
        txtAddress.setText(patient.getAddress());
        txtPatientEmail.setText(patient.getPatientEmail());
        
        String sex = patient.getGender();
        
        if (sex.equals("Male")) {
            radioBtnMale.setSelected(true);
        } else if (sex.equals("Female")) {
            radioBtnFemale.setSelected(true);
        } 
    }
    
    private boolean usernamePatternCorrect(String username) {
        Pattern p = Pattern.compile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$");
        Matcher m = p.matcher(username);
        boolean b = m.matches();
        return b;
        
    }
    
    private boolean checkEmailDuplication(String patientEmail){
             boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<Network> networks = ecosystem.getNetworks();
        List<HealthCareEnterprise> healthCenterEnterprises = new ArrayList<>();
        
        for (Network network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCareEnterprise) {
                    healthCenterEnterprises.add((HealthCareEnterprise) enterprise);
                }
            }
        }
        
        for (HealthCareEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<PawPatient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (PawPatient patient : patients) {
                if (patientEmail.equals(patient.getPatientEmail())) {
                    isPatientFound = true;
                    break;
                }
                
            }
        }
        return isPatientFound;
    }
}
