package userinterface.InsuranceAgentRole;

import model.enterprise.Enterprise;
import model.organization.InsuranceAgentOrganization;
import model.organization.Organization;
import model.userAccount.User;
import java.awt.CardLayout;
import java.util.UUID;
import javax.swing.JPanel;

public class InsuranceAgentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAgentWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private User userAccount;
    private InsuranceAgentOrganization insuranceAgentOrganization;
    private Enterprise enterprise;

    public InsuranceAgentWorkAreaJPanel(JPanel jpanel, User userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = jpanel;
        this.userAccount = userAccount;
        this.insuranceAgentOrganization = (InsuranceAgentOrganization) organization;
        this.enterprise = enterprise;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewUser = new javax.swing.JButton();
        btnProcessInsuranceRequests = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnAddNewUser.setBackground(new java.awt.Color(102, 102, 0));
        btnAddNewUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewUser.setText("Add New Customer");
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });
        add(btnAddNewUser);
        btnAddNewUser.setBounds(60, 280, 184, 41);

        btnProcessInsuranceRequests.setBackground(new java.awt.Color(102, 102, 0));
        btnProcessInsuranceRequests.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcessInsuranceRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessInsuranceRequests.setText("Process Insurance Requests");
        btnProcessInsuranceRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessInsuranceRequestsActionPerformed(evt);
            }
        });
        add(btnProcessInsuranceRequests);
        btnProcessInsuranceRequests.setBounds(350, 280, 200, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insaurance3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-60, 50, 690, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        String policyNumber = UUID.randomUUID().toString().substring(0, 7);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddNewPolicyHolderJPanel", new AddNewPolicyHolderJPanel(userProcessContainer, userAccount, enterprise, policyNumber));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnAddNewUserActionPerformed

    private void btnProcessInsuranceRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ProcessInsuranceRequestsJPanel", new AllInsuranceRequestsJPanel(userProcessContainer, userAccount, enterprise, insuranceAgentOrganization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessInsuranceRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnProcessInsuranceRequests;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
